version: '3.9'
services:
  fe:
    image: whoishu/ssul-front:0.1
    container_name: ssul-front
    ports:
      - '80:80'
  be:
    image: whoishu/ssul-api:0.1
    container_name: ssul-api
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
